services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - AI_SERVICE_URL=http://ai-service:5000/process
    networks:
      - app-network
    depends_on:
      - ai-service
    restart: unless-stopped

  ai-service:
    build: ./ai-service
    ports:
      - "5001:5000"  # Порт 5001 на хосте
    networks:
      - app-network
    environment:
      - DEEPSEEK_API_KEY=sk-7d5ddde5e74d4e089dfaad352e4bcbc0
      - DEEPSEEK_MODEL=deepseek-chat
    restart: on-failure

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://localhost:5001
    depends_on:
      - backend
    restart: unless-stopped

networks:
  app-network:
    driver: bridge