services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - AI_SERVICE_URL=http://ai-service:5000/process
    depends_on:
      - ai-service
    restart: unless-stopped

  ai-service:
    build: ./ai-service
    ports:
      - "5001:5000"  # Порт 5001 на хосте
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    restart: on-failure

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 3G
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11434/api/tags" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5001
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  ollama-data: