services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - AI_SERVICE_URL=http://ai-service:5000/process
    networks:
      - app-network
    depends_on:
      - ai-service
    restart: unless-stopped

  ai-service:
    build: ./ai-service
    ports:
      - "5001:5000"
    networks:
      - app-network
    environment:
      - DEEPSEEK_API_KEY=sk-e997ae4e616585fa09ad825ac49eb8d1a30e56fb4e311c73a69869e64ea81768
      - DEEPSEEK_MODEL=deepseek-chat
      - DEEPSEEK_API_URL=https://api.deepseek.com/v1
    restart: on-failure

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://localhost:5001
    depends_on:
      - backend
    restart: unless-stopped

  demo-site:
    build: ./demo-site
    ports:
      - "8001:80"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge